### ISSUE TITLE
Graal check in desktop helper may be flipped?

### ISSUE THREAD

**Issue by tommyettinger** [crykn/guacamole#2]
[I had copied this](https://github.com/crykn/guacamole/blob/master/gdx-desktop/src/main/java/de/damios/guacamole/gdx/StartOnFirstThreadHelper.java#L79-L82) from Guacamole into new gdx-liftoff projects (and Liftoff itself), but the check of the Graal Native Image property seems wrong. It will return `""` if the property is not found, so since we only want to exist early if the property *was* found, the isEmpty() check should be negated. This has been tested on Mac with a beta release of gdx-liftoff, https://github.com/tommyettinger/gdx-liftoff/issues/136 , and the negation allows the app to run again.

**Comment by crykn** [comment]
Thanks for catching this!
